# Generated by Django 6.0.3 on 2026-03-18 06:45

import datetime
import django.db.models.deletion
import web.models.character
import web.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_userprofile_update_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="photo",
            field=models.ImageField(
                default="user/photos/default.png",
                upload_to=web.models.user.photo_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile",
            field=models.TextField(default="谢谢你的关注", max_length=500),
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "photo",
                    models.ImageField(upload_to=web.models.character.photo_upload_to),
                ),
                ("profile", models.TextField(max_length=100000)),
                (
                    "background_image",
                    models.ImageField(upload_to=web.models.character.photo_upload_to),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2026, 3, 18, 6, 45, 28, 924416, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2026, 3, 18, 6, 45, 28, 924416, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.userprofile",
                    ),
                ),
            ],
        ),
    ]
