# Generated by Django 6.0.3 on 2026-03-18 06:49

import django.utils.timezone
import web.models.character
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_alter_userprofile_photo_alter_userprofile_profile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="background_image",
            field=models.ImageField(
                upload_to=web.models.character.background_image_upload_to
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="create_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="character",
            name="update_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
